const COLOR_ACTIVE = 0x4169e1;
const COLOR_HOVERED = 0xef4444;
const COLOR_BRUSHED = 0xfb923c;
const COLOR_FILTERED = 0xcbd5e0;

export { COLOR_ACTIVE, COLOR_HOVERED, COLOR_BRUSHED, COLOR_FILTERED };
